# Generated by Django 5.1.3 on 2024-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('encrypted_secret', models.BinaryField()),
                ('encrypted_passphrase', models.BinaryField()),
                ('ttl', models.DateTimeField()),
            ],
        ),
    ]
