# Generated by Django 5.1.3 on 2024-11-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='encryption_key',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
