# Generated by Django 5.1.3 on 2024-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0002_secret_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='encryption_key',
            field=models.CharField(max_length=255),
        ),
    ]
