# Generated by Django 5.1.3 on 2024-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0003_alter_secret_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='encryption_key',
            field=models.CharField(default='No generated key', max_length=255, unique=True),
        ),
    ]
